services:
  postgres_db:
    image: postgres:16
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'

  app:
    build: 
      context: .  
      dockerfile: Dockerfile
    ports:
      - '${NEXT_APP_PORT}:3000'
    stdin_open: true
    tty: true
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      # Opcional: desativar migrações se necessário
      # SKIP_MIGRATIONS: "true"
      NODE_ENV: production
      DATABASE_URL: "${DATABASE_URL}"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      AUTH_TRUST_HOST: "${AUTH_TRUST_HOST}"
    networks:
      - prisma-network

  prisma-studio:
    image: node:lts-alpine3.17
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "npm install -g pnpm && 
             pnpm exec prisma studio --port 5555 --browser none"
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    networks:
      - prisma-network
    depends_on:
      postgres_db:
        condition: service_healthy
      app:
        condition: service_started

networks:
  prisma-network:
    name: prisma-network

volumes:
  postgres_data: 