services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    env_file:
      - .env
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: always
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      # importante: host do banco deve ser "postgres_db"
      DATABASE_URL: ${DATABASE_URL}
      AUTH_URL: '${AUTH_URL}'
      AUTH_SECRET: '${AUTH_SECRET}'
      AUTH_TRUST_HOST: '${AUTH_TRUST_HOST}'
    networks:
      - app-network
    stdin_open: true
    tty: true
    env_file:
      - .env

networks:
  app-network:
    name: app-network

volumes:
  postgres_data:
