services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ourwedding?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=seu_nextauth_secret_aqui
    volumes:
      - ./.env:/app/.env
      - ./public:/app/public
      - ./scripts:/app/scripts

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ourwedding
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 